CHUNK_SIZE: 1024
CHANNELS: 1
SAMPLE_RATE: 16000
THRESHOLD: 1000
SILENCE_LIMIT: 1.2
INPUT_AUDIO_FILE: "input.wav"
OUTPUT_AUDIO_FILE: "output.wav"
LANG: "en-US"
ENCODING: "LINEAR16"
ACCENT: "en-US-Neural2-C"
GENDER: "FEMALE"

TOKEN_LIFE: 3600